openapi: 3.0.3
info:
    title: Goa API
    description: The Kubernetes Federated Credential Api
    version: 0.0.1
servers:
    - url: http://0.0.0.0:8088
paths:
    /exchangeToken:
        post:
            tags:
                - tokenExchange
            summary: exchangeToken tokenExchange
            operationId: tokenExchange#exchangeToken
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/ExchangeTokenRequestBody'
                        example:
                            jwt: Rerum quia non et.
                            namespace: Commodi eveniet a consectetur.
                            serviceAccountName: Et illum qui aut.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/StatusResult'
                            example:
                                status:
                                    token: Et ab commodi voluptate eligendi non temporibus.
components:
    schemas:
        ExchangeTokenRequestBody:
            type: object
            properties:
                jwt:
                    type: string
                    description: The JWT Token from the impersonating service account
                    example: Fugiat incidunt omnis mollitia fugit architecto qui.
                namespace:
                    type: string
                    description: The target namespace for impersonation
                    example: Molestiae animi ab.
                serviceAccountName:
                    type: string
                    description: The target serviceAccount
                    example: Officia expedita magnam et enim.
            example:
                jwt: Maiores unde.
                namespace: Qui voluptas ad quis sit voluptates tempora.
                serviceAccountName: Molestiae ad error voluptas.
        Status:
            type: object
            properties:
                token:
                    type: string
                    description: The status token
                    example: Est alias harum ut quis quod totam.
            description: Status with a token.
            example:
                token: Iste numquam veritatis aut quas.
            required:
                - token
        StatusResult:
            type: object
            properties:
                status:
                    $ref: '#/components/schemas/Status'
            example:
                status:
                    token: Et ab commodi voluptate eligendi non temporibus.
            required:
                - status
tags:
    - name: livez
    - name: readyz
    - name: tokenExchange
      description: Exchange an incoming Kubernetes Token for Another Kubernetes Token
