swagger: "2.0"
info:
    title: ""
    description: The Kubernetes Federated Credential Api
    version: 0.0.1
host: localhost:8088
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /exchangeToken:
        post:
            tags:
                - tokenExchange
            summary: exchangeToken tokenExchange
            operationId: tokenExchange#exchangeToken
            parameters:
                - name: ExchangeTokenRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/TokenExchangeExchangeTokenRequestBody'
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: string
            schemes:
                - http
definitions:
    TokenExchangeExchangeTokenRequestBody:
        title: TokenExchangeExchangeTokenRequestBody
        type: object
        properties:
            jwt:
                type: string
                description: The JWT Token from the impersonating service account
                example: Ut et itaque quod.
            namespace:
                type: string
                description: The target namespace for impersonation
                example: Deleniti qui.
            serviceAccountName:
                type: string
                description: The target serviceAccount
                example: Ex deleniti.
        example:
            jwt: Neque occaecati distinctio nihil ut.
            namespace: Consectetur est non ducimus fuga.
            serviceAccountName: Neque commodi.
